cpmaddpackage(
  NAME jsoncpp
  GITHUB_REPOSITORY open-source-parsers/jsoncpp
  GIT_TAG 1.9.8
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
  OPTIONS
    "JSONCPP_WITH_TESTS OFF"
    "JSONCPP_WITH_POST_BUILD_UNITTEST OFF"
    "JSONCPP_WITH_EXAMPLE OFF"
    "JSONCPP_WITH_PKGCONFIG_SUPPORT OFF"
    "JSONCPP_WITH_CMAKE_PACKAGE OFF"
    "JSONCPP_WITH_STRICT_ISO OFF"
    "JSONCPP_WITH_WARNING_AS_ERROR OFF"
    "BUILD_SHARED_LIBS OFF"
    "BUILD_STATIC_LIBS ON"
    "BUILD_OBJECT_LIBS OFF"
)