cpmaddpackage(
    NAME
    tinyobjloader
    GITHUB_REPOSITORY
    tinyobjloader/tinyobjloader
    GIT_TAG
    release
    SYSTEM
    ON
    GIT_SHALLOW
    ON
    EXCLUDE_FROM_ALL
    ON
    OPTIONS
    "TINYOBJLOADER_BUILD_SHARED_LIBS OFF"
    "BUILD_SHARED_LIBS OFF"
    "TINYOBJLOADER_BUILD_TEST_LOADER OFF"
    "TINYOBJLOADER_BUILD_OBJ_STICHER OFF"
    "TINYOBJLOADER_WITH_PYTHON OFF"
    "TINYOBJLOADER_USE_DOUBLE OFF")
