# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: nix_ci

on:
  pull_request:
    paths: &nix_paths
      - "nix/**"
      - "!nix/**/*.md"
      - ".github/workflows/nix.yml"
  push:
    branches: [main]
    paths: *nix_paths
  workflow_dispatch:

concurrency:
  group: nix_ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  nix_build:
    name: linux_nix_x86_64
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check flake
        run: nix flake check ./nix --no-write-lock-file
      - name: Build OCI image
        run: nix build ./nix#docker --no-link --no-write-lock-file
